# Generated by Django 4.0 on 2023-09-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_core', '0002_externalassetaccount_and_more'),
        ('service_wallet', '0001_initial'),
        ('service_markets', '0005_alter_market_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_icon', models.URLField(blank=True, max_length=150, null=True)),
                ('service_url', models.URLField()),
                ('transaction_types', models.JSONField(default=list, max_length=20)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Failed'), (0, 'Pending'), (1, 'Successful')], default=0)),
                ('verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('transaction_type', models.CharField(default='outbound', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_markets.asset')),
                ('destination', models.ForeignKey(default='External Account', on_delete=django.db.models.deletion.SET_DEFAULT, to='service_core.externalassetaccount')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_wallet.wallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Failed'), (0, 'Pending'), (1, 'Successful')], default=0)),
                ('verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('transaction_type', models.CharField(default='inbound', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_markets.asset')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_wallet.wallet')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_transaction.paymentgateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
