# Generated by Django 4.0 on 2023-09-10 17:57

from django.db import migrations, models
import django.db.models.deletion
import service_verification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_core', '0002_externalassetaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Initiated'), (1, 'Approved'), (-1, 'Rejected')], default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('passport', 'International Passport'), ('license', "Driver's License")], max_length=20)),
                ('id_document', models.FileField(null=True, upload_to='verification_documents/')),
                ('review_notes', models.TextField()),
                ('reviewed_by', models.ForeignKey(on_delete=models.SET(service_verification.models.get_sentinel_user), related_name='reviewed_by', to='service_core.customuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_core.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BVN_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Initiated'), (1, 'Approved'), (-1, 'Rejected')], default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('bvn', models.CharField(max_length=15, unique=True)),
                ('bvn_access_authorization', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_core.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
