# Generated by Django 4.0 on 2023-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvn_verification',
            name='max_attempt',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='id_verification',
            name='max_attempt',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bvn_verification',
            name='bvn_access_authorization',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bvn_verification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='id_verification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
