# Generated by Django 4.0 on 2023-12-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_verification', '0004_rename_max_attempt_bvn_verification_attempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bvn_verification',
            old_name='bvn',
            new_name='id_number',
        ),
        migrations.RemoveField(
            model_name='id_verification',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='id_verification',
            name='id_number',
            field=models.CharField(default=123456, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='id_verification',
            name='method',
            field=models.CharField(choices=[('passport', 'International Passport'), ('nin', 'National Identification')], max_length=20),
        ),
    ]
