# Generated by Django 4.0 on 2023-12-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_verification', '0005_rename_bvn_bvn_verification_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvn_verification',
            name='attempt',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='id_verification',
            name='attempt',
            field=models.SmallIntegerField(default=1),
        ),
    ]
