# Generated by Django 4.0 on 2023-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='baseasset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
