# Generated by Django 4.0 on 2023-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_markets', '0002_alter_asset_metadata_alter_baseasset_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('fiat', 'Fiat'), ('digital', 'Digital')], default='digital', max_length=7),
        ),
        migrations.AddField(
            model_name='baseasset',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseasset',
            name='asset_type',
            field=models.CharField(choices=[('fiat', 'Fiat'), ('digital', 'Digital')], default='digital', max_length=7),
        ),
    ]
