# Generated by Django 4.0 on 2023-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_markets', '0003_asset_asset_type_baseasset_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseasset',
            name='market_value',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=30),
        ),
    ]
