# Generated by Django 4.0 on 2023-09-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_markets', '0004_baseasset_market_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'default_permissions': ('add', 'view'), 'get_latest_by': 'timestamp'},
        ),
    ]
