# Generated by Django 4.0 on 2023-09-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_core', '0002_externalassetaccount_and_more'),
        ('service_markets', '0005_alter_market_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('based_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_markets.baseasset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_core.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='AssetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_markets.asset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='service_wallet.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetbalance',
            constraint=models.UniqueConstraint(fields=('wallet', 'asset'), name='wallet_asset_unique'),
        ),
    ]
