# Generated by Django 4.0 on 2023-11-23 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbalance',
            name='balance',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=29),
        ),
        migrations.AlterField(
            model_name='assetbalance',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_asset', to='service_wallet.wallet'),
        ),
    ]
